### ISSUE TITLE
First time redirection is not happening...

### ISSUE THREAD

**Issue by ulhasshelke** [reillo/mage_customerredirect#1]
First time redirection is not happening... once you tried to login its redirecting to default store and then logged out, and tried again then its working.  Also in Customer Configuration setting I have set "No" to "Redirect Customer to Account Dashboard after Logging in" option, but still its redirecting to dashboard. please let me know how to solve this.

I'm using magneto 1.9.2.4

**Comment by ulhasshelke** [comment]
Done.

I have replaced this URL :
$session->setAfterAuthUrl($url);

with:
$session->setBeforeAuthUrl($url);

Thanks :)

**Comment by reillo** [comment]
Hi @ulhasshelke, thanks for addressing this issue. 

On some instances, some extensions might use `setAfterAuthUrl` which overrides `setBeforeAuthUrl`. I both set the before and after auth url to force the auth url redirection to use ours. Please see related above commit and will try to test this tomorrow. 

thanks,

**Comment by reillo** [comment]
This one is tested.
